import { ImageRequireSource } from "react-native";

export const Countries = {
  ad: "Andorra",
  ae: "United Arab Emirates",
  af: "Afghanistan",
  ag: "Antigua and Barbuda",
  ai: "Anguilla",
  al: "Albania",
  am: "Armenia",
  an: "Netherlands Antilles",
  ao: "Angola",
  aq: "Antarctica",
  ar: "Argentina",
  as: "American Samoa",
  at: "Austria",
  au: "Australia",
  aw: "Aruba",
  ax: "Aland Islands",
  az: "Azerbaijan",
  ba: "Bosnia and Herzegovina",
  bb: "Barbados",
  bd: "Bangladesh",
  be: "Belgium",
  bf: "Burkina Faso",
  bg: "Bulgaria",
  bh: "Bahrain",
  bi: "Burundi",
  bj: "Benin",
  bm: "Bermuda",
  bn: "Brunei Darussalam",
  bo: "Bolivia",
  br: "Brazil",
  bs: "Bahamas",
  bt: "Bhutan",
  bv: "Bouvet Island",
  bw: "Botswana",
  by: "Belarus",
  bz: "Belize",
  ca: "Canada",
  cc: "Cocos (Keeling) Islands",
  cd: "Congo, The Democratic Republic of the",
  cf: "Central African Republic",
  cg: "Congo",
  ch: "Switzerland",
  ci: "Ivory Coast",
  ck: "Cook Islands",
  cl: "Chile",
  cm: "Cameroon",
  cn: "China",
  co: "Colombia",
  cr: "Costa Rica",
  cu: "Cuba",
  cv: "Cape Verde",
  cx: "Christmas Island",
  cy: "Cyprus",
  cz: "Czech Republic",
  de: "Germany",
  dj: "Djibouti",
  dk: "Denmark",
  dm: "Dominica",
  do: "Dominican Republic",
  dz: "Algeria",
  ec: "Ecuador",
  ee: "Estonia",
  eg: "Egypt",
  eh: "Western Sahara",
  er: "Eritrea",
  es: "Spain",
  et: "Ethiopia",
  eu: "Europe",
  fi: "Finland",
  fj: "Fiji",
  fk: "Falkland Islands (Malvinas)",
  fm: "Micronesia, Federated States of",
  fo: "Faroe Islands",
  fr: "France",
  ga: "Gabon",
  gb: "United Kingdom",
  gd: "Grenada",
  ge: "Georgia",
  gf: "French Guiana",
  gg: "Guernsey",
  gh: "Ghana",
  gi: "Gibraltar",
  gl: "Greenland",
  gm: "Gambia",
  gn: "Guinea",
  gp: "Guadeloupe",
  gq: "Equatorial Guinea",
  gr: "Greece",
  gs: "South Georgia and the South Sandwich Islands",
  gt: "Guatemala",
  gu: "Guam",
  gw: "Guinea-Bissau",
  gy: "Guyana",
  hk: "Hong Kong",
  hm: "Heard Island and McDonald Islands",
  hn: "Honduras",
  hr: "Croatia",
  ht: "Haiti",
  hu: "Hungary",
  id: "Indonesia",
  ie: "Ireland",
  il: "Israel",
  im: "Isle of Man",
  in: "India",
  io: "British Indian Ocean Territory",
  iq: "Iraq",
  ir: "Iran",
  is: "Iceland",
  it: "Italy",
  je: "Jersey",
  jm: "Jamaica",
  jo: "Jordan",
  jp: "Japan",
  ke: "Kenya",
  kg: "Kyrgyzstan",
  kh: "Cambodia",
  ki: "Kiribati",
  km: "Comoros",
  kn: "Saint Kitts and Nevis",
  kp: "North Korea",
  kr: "South Korea",
  kw: "Kuwait",
  ky: "Cayman Islands",
  kz: "Kazakhstan",
  la: "Lao People's Democratic Republic",
  lb: "Lebanon",
  lc: "Saint Lucia",
  li: "Liechtenstein",
  lk: "Sri Lanka",
  lr: "Liberia",
  ls: "Lesotho",
  lt: "Lithuania",
  lu: "Luxembourg",
  lv: "Latvia",
  ly: "Libya",
  ma: "Morocco",
  mc: "Monaco",
  md: "Moldova",
  me: "Montenegro",
  mg: "Madagascar",
  mh: "Marshall Islands",
  mk: "Macedonia",
  ml: "Mali",
  mm: "Myanmar",
  mn: "Mongolia",
  mo: "Macau",
  mp: "Northern Mariana Islands",
  mq: "Martinique",
  mr: "Mauritania",
  ms: "Montserrat",
  mt: "Malta",
  mu: "Mauritius",
  mv: "Maldives",
  mw: "Malawi",
  mx: "Mexico",
  my: "Malaysia",
  mz: "Mozambique",
  na: "Namibia",
  nc: "New Caledonia",
  ne: "Niger",
  nf: "Norfolk Island",
  ng: "Nigeria",
  ni: "Nicaragua",
  nl: "Netherlands",
  no: "Norway",
  np: "Nepal",
  nr: "Nauru",
  nu: "Niue",
  nz: "New Zealand",
  om: "Oman",
  pa: "Panama",
  pe: "Peru",
  pf: "French Polynesia",
  pg: "Papua New Guinea",
  ph: "Philippines",
  pk: "Pakistan",
  pl: "Poland",
  pm: "Saint Pierre and Miquelon",
  pn: "Pitcairn Islands",
  pr: "Puerto Rico",
  ps: "Palestinian Territory",
  pt: "Portugal",
  pw: "Palau",
  py: "Paraguay",
  qa: "Qatar",
  re: "Reunion",
  ro: "Romania",
  rs: "Serbia",
  ru: "Russia",
  rw: "Rwanda",
  sa: "Saudi Arabia",
  sb: "Solomon Islands",
  sc: "Seychelles",
  sd: "Sudan",
  se: "Sweden",
  sg: "Singapore",
  sh: "Saint Helena",
  si: "Slovenia",
  sj: "Svalbard and Jan Mayen",
  sk: "Slovakia",
  sl: "Sierra Leone",
  sm: "San Marino",
  sn: "Senegal",
  so: "Somalia",
  sr: "Suriname",
  st: "São Tomé and Príncipe",
  sv: "El Salvador",
  sy: "Syria",
  sz: "Swaziland",
  tc: "Turks and Caicos Islands",
  td: "Chad",
  tf: "French Southern Territories",
  tg: "Togo",
  th: "Thailand",
  tj: "Tajikistan",
  tk: "Tokelau",
  tl: "Timor-Leste",
  tm: "Turkmenistan",
  tn: "Tunisia",
  to: "Tonga",
  tr: "Turkey",
  tt: "Trinidad and Tobago",
  tv: "Tuvalu",
  tw: "Taiwan",
  tz: "Tanzania",
  ua: "Ukraine",
  ug: "Uganda",
  um: "United States Minor Outlying Islands",
  us: "United States",
  uy: "Uruguay",
  uz: "Uzbekistan",
  va: "Holy See (Vatican City State)",
  vc: "Saint Vincent and the Grenadines",
  ve: "Venezuela",
  vg: "British Virgin Islands",
  vi: "U.S. Virgin Islands",
  vn: "Vietnam",
  vu: "Vanuatu",
  wf: "Wallis and Futuna",
  ws: "Samoa",
  ye: "Yemen",
  yt: "Mayotte",
  za: "South Africa",
  zm: "Zambia",
  zw: "Zimbabwe",
};

export type CountryCode = keyof typeof Countries;
export type CountryImage = ImageRequireSource;

export const CountriesImages: Record<CountryCode, CountryImage> = {
  ad: require("../assets/flags/ad.png"),
  ae: require("../assets/flags/ae.png"),
  af: require("../assets/flags/af.png"),
  ag: require("../assets/flags/ag.png"),
  ai: require("../assets/flags/ai.png"),
  al: require("../assets/flags/al.png"),
  am: require("../assets/flags/am.png"),
  an: require("../assets/flags/an.png"),
  ao: require("../assets/flags/ao.png"),
  aq: require("../assets/flags/aq.png"),
  ar: require("../assets/flags/ar.png"),
  as: require("../assets/flags/as.png"),
  at: require("../assets/flags/at.png"),
  au: require("../assets/flags/au.png"),
  aw: require("../assets/flags/aw.png"),
  ax: require("../assets/flags/ax.png"),
  az: require("../assets/flags/az.png"),
  ba: require("../assets/flags/ba.png"),
  bb: require("../assets/flags/bb.png"),
  bd: require("../assets/flags/bd.png"),
  be: require("../assets/flags/be.png"),
  bf: require("../assets/flags/bf.png"),
  bg: require("../assets/flags/bg.png"),
  bh: require("../assets/flags/bh.png"),
  bi: require("../assets/flags/bi.png"),
  bj: require("../assets/flags/bj.png"),
  bm: require("../assets/flags/bm.png"),
  bn: require("../assets/flags/bn.png"),
  bo: require("../assets/flags/bo.png"),
  br: require("../assets/flags/br.png"),
  bs: require("../assets/flags/bs.png"),
  bt: require("../assets/flags/bt.png"),
  bv: require("../assets/flags/bv.png"),
  bw: require("../assets/flags/bw.png"),
  by: require("../assets/flags/by.png"),
  bz: require("../assets/flags/bz.png"),
  ca: require("../assets/flags/ca.png"),
  cc: require("../assets/flags/cc.png"),
  cd: require("../assets/flags/cd.png"),
  cf: require("../assets/flags/cf.png"),
  cg: require("../assets/flags/cg.png"),
  ch: require("../assets/flags/ch.png"),
  ci: require("../assets/flags/ci.png"),
  ck: require("../assets/flags/ck.png"),
  cl: require("../assets/flags/cl.png"),
  cm: require("../assets/flags/cm.png"),
  cn: require("../assets/flags/cn.png"),
  co: require("../assets/flags/co.png"),
  cr: require("../assets/flags/cr.png"),
  cu: require("../assets/flags/cu.png"),
  cv: require("../assets/flags/cv.png"),
  cx: require("../assets/flags/cx.png"),
  cy: require("../assets/flags/cy.png"),
  cz: require("../assets/flags/cz.png"),
  de: require("../assets/flags/de.png"),
  dj: require("../assets/flags/dj.png"),
  dk: require("../assets/flags/dk.png"),
  dm: require("../assets/flags/dm.png"),
  do: require("../assets/flags/do.png"),
  dz: require("../assets/flags/dz.png"),
  ec: require("../assets/flags/ec.png"),
  ee: require("../assets/flags/ee.png"),
  eg: require("../assets/flags/eg.png"),
  eh: require("../assets/flags/eh.png"),
  er: require("../assets/flags/er.png"),
  es: require("../assets/flags/es.png"),
  et: require("../assets/flags/et.png"),
  eu: require("../assets/flags/eu.png"),
  fi: require("../assets/flags/fi.png"),
  fj: require("../assets/flags/fj.png"),
  fk: require("../assets/flags/fk.png"),
  fm: require("../assets/flags/fm.png"),
  fo: require("../assets/flags/fo.png"),
  fr: require("../assets/flags/fr.png"),
  ga: require("../assets/flags/ga.png"),
  gb: require("../assets/flags/gb.png"),
  gd: require("../assets/flags/gd.png"),
  ge: require("../assets/flags/ge.png"),
  gf: require("../assets/flags/gf.png"),
  gg: require("../assets/flags/gg.png"),
  gh: require("../assets/flags/gh.png"),
  gi: require("../assets/flags/gi.png"),
  gl: require("../assets/flags/gl.png"),
  gm: require("../assets/flags/gm.png"),
  gn: require("../assets/flags/gn.png"),
  gp: require("../assets/flags/gp.png"),
  gq: require("../assets/flags/gq.png"),
  gr: require("../assets/flags/gr.png"),
  gs: require("../assets/flags/gs.png"),
  gt: require("../assets/flags/gt.png"),
  gu: require("../assets/flags/gu.png"),
  gw: require("../assets/flags/gw.png"),
  gy: require("../assets/flags/gy.png"),
  hk: require("../assets/flags/hk.png"),
  hm: require("../assets/flags/hm.png"),
  hn: require("../assets/flags/hn.png"),
  hr: require("../assets/flags/hr.png"),
  ht: require("../assets/flags/ht.png"),
  hu: require("../assets/flags/hu.png"),
  id: require("../assets/flags/id.png"),
  ie: require("../assets/flags/ie.png"),
  il: require("../assets/flags/il.png"),
  im: require("../assets/flags/im.png"),
  in: require("../assets/flags/in.png"),
  io: require("../assets/flags/io.png"),
  iq: require("../assets/flags/iq.png"),
  ir: require("../assets/flags/ir.png"),
  is: require("../assets/flags/is.png"),
  it: require("../assets/flags/it.png"),
  je: require("../assets/flags/je.png"),
  jm: require("../assets/flags/jm.png"),
  jo: require("../assets/flags/jo.png"),
  jp: require("../assets/flags/jp.png"),
  ke: require("../assets/flags/ke.png"),
  kg: require("../assets/flags/kg.png"),
  kh: require("../assets/flags/kh.png"),
  ki: require("../assets/flags/ki.png"),
  km: require("../assets/flags/km.png"),
  kn: require("../assets/flags/kn.png"),
  kp: require("../assets/flags/kp.png"),
  kr: require("../assets/flags/kr.png"),
  kw: require("../assets/flags/kw.png"),
  ky: require("../assets/flags/ky.png"),
  kz: require("../assets/flags/kz.png"),
  la: require("../assets/flags/la.png"),
  lb: require("../assets/flags/lb.png"),
  lc: require("../assets/flags/lc.png"),
  li: require("../assets/flags/li.png"),
  lk: require("../assets/flags/lk.png"),
  lr: require("../assets/flags/lr.png"),
  ls: require("../assets/flags/ls.png"),
  lt: require("../assets/flags/lt.png"),
  lu: require("../assets/flags/lu.png"),
  lv: require("../assets/flags/lv.png"),
  ly: require("../assets/flags/ly.png"),
  ma: require("../assets/flags/ma.png"),
  mc: require("../assets/flags/mc.png"),
  md: require("../assets/flags/md.png"),
  me: require("../assets/flags/me.png"),
  mg: require("../assets/flags/mg.png"),
  mh: require("../assets/flags/mh.png"),
  mk: require("../assets/flags/mk.png"),
  ml: require("../assets/flags/ml.png"),
  mm: require("../assets/flags/mm.png"),
  mn: require("../assets/flags/mn.png"),
  mo: require("../assets/flags/mo.png"),
  mp: require("../assets/flags/mp.png"),
  mq: require("../assets/flags/mq.png"),
  mr: require("../assets/flags/mr.png"),
  ms: require("../assets/flags/ms.png"),
  mt: require("../assets/flags/mt.png"),
  mu: require("../assets/flags/mu.png"),
  mv: require("../assets/flags/mv.png"),
  mw: require("../assets/flags/mw.png"),
  mx: require("../assets/flags/mx.png"),
  my: require("../assets/flags/my.png"),
  mz: require("../assets/flags/mz.png"),
  na: require("../assets/flags/na.png"),
  nc: require("../assets/flags/nc.png"),
  ne: require("../assets/flags/ne.png"),
  nf: require("../assets/flags/nf.png"),
  ng: require("../assets/flags/ng.png"),
  ni: require("../assets/flags/ni.png"),
  nl: require("../assets/flags/nl.png"),
  no: require("../assets/flags/no.png"),
  np: require("../assets/flags/np.png"),
  nr: require("../assets/flags/nr.png"),
  nu: require("../assets/flags/nu.png"),
  nz: require("../assets/flags/nz.png"),
  om: require("../assets/flags/om.png"),
  pa: require("../assets/flags/pa.png"),
  pe: require("../assets/flags/pe.png"),
  pf: require("../assets/flags/pf.png"),
  pg: require("../assets/flags/pg.png"),
  ph: require("../assets/flags/ph.png"),
  pk: require("../assets/flags/pk.png"),
  pl: require("../assets/flags/pl.png"),
  pm: require("../assets/flags/pm.png"),
  pn: require("../assets/flags/pn.png"),
  pr: require("../assets/flags/pr.png"),
  ps: require("../assets/flags/ps.png"),
  pt: require("../assets/flags/pt.png"),
  pw: require("../assets/flags/pw.png"),
  py: require("../assets/flags/py.png"),
  qa: require("../assets/flags/qa.png"),
  re: require("../assets/flags/re.png"),
  ro: require("../assets/flags/ro.png"),
  rs: require("../assets/flags/rs.png"),
  ru: require("../assets/flags/ru.png"),
  rw: require("../assets/flags/rw.png"),
  sa: require("../assets/flags/sa.png"),
  sb: require("../assets/flags/sb.png"),
  sc: require("../assets/flags/sc.png"),
  sd: require("../assets/flags/sd.png"),
  se: require("../assets/flags/se.png"),
  sg: require("../assets/flags/sg.png"),
  sh: require("../assets/flags/sh.png"),
  si: require("../assets/flags/si.png"),
  sj: require("../assets/flags/sj.png"),
  sk: require("../assets/flags/sk.png"),
  sl: require("../assets/flags/sl.png"),
  sm: require("../assets/flags/sm.png"),
  sn: require("../assets/flags/sn.png"),
  so: require("../assets/flags/so.png"),
  sr: require("../assets/flags/sr.png"),
  st: require("../assets/flags/st.png"),
  sv: require("../assets/flags/sv.png"),
  sy: require("../assets/flags/sy.png"),
  sz: require("../assets/flags/sz.png"),
  tc: require("../assets/flags/tc.png"),
  td: require("../assets/flags/td.png"),
  tf: require("../assets/flags/tf.png"),
  tg: require("../assets/flags/tg.png"),
  th: require("../assets/flags/th.png"),
  tj: require("../assets/flags/tj.png"),
  tk: require("../assets/flags/tk.png"),
  tl: require("../assets/flags/tl.png"),
  tm: require("../assets/flags/tm.png"),
  tn: require("../assets/flags/tn.png"),
  to: require("../assets/flags/to.png"),
  tr: require("../assets/flags/tr.png"),
  tt: require("../assets/flags/tt.png"),
  tv: require("../assets/flags/tv.png"),
  tw: require("../assets/flags/tw.png"),
  tz: require("../assets/flags/tz.png"),
  ua: require("../assets/flags/ua.png"),
  ug: require("../assets/flags/ug.png"),
  um: require("../assets/flags/um.png"),
  us: require("../assets/flags/us.png"),
  uy: require("../assets/flags/uy.png"),
  uz: require("../assets/flags/uz.png"),
  va: require("../assets/flags/va.png"),
  vc: require("../assets/flags/vc.png"),
  ve: require("../assets/flags/ve.png"),
  vg: require("../assets/flags/vg.png"),
  vi: require("../assets/flags/vi.png"),
  vn: require("../assets/flags/vn.png"),
  vu: require("../assets/flags/vu.png"),
  wf: require("../assets/flags/wf.png"),
  ws: require("../assets/flags/ws.png"),
  ye: require("../assets/flags/ye.png"),
  yt: require("../assets/flags/yt.png"),
  za: require("../assets/flags/za.png"),
  zm: require("../assets/flags/zm.png"),
  zw: require("../assets/flags/zw.png"),
};
