const COUNTRIES = {
    Albania: '',
    Algeria: '',
    'American Samoa': '',
    Andorra: '',
    Angola: '',
    'Antigua and Barbuda': '',
    Argentina: '',
    Armenia: '',
    Australia: '',
    Austria: '',
    Azerbaijan: '',
    Bahamas: '',
    Bahrain: '',
    Bangladesh: '',
    Barbados: '',
    Belarus: '',
    Belgium: '',
    Benin: '',
    Bermuda: '',
    Bhutan: '',
    'Bosnia and Herzegovina': '',
    Botswana: '',
    Brazil: '',
    'British Virgin Islands': '',
    Bulgaria: '',
    'Burkina Faso': '',
    Burundi: '',
    Canada: '',
    'Cayman Islands': '',
    Chad: '',
    Chile: '',
    China: '',
    Taiwan: '',
    Colombia: '',
    'Cook Islands': '',
    'Costa Rica': '',
    Croatia: '',
    Cuba: '',
    Cyprus: '',
    'Czech Republic': '',
    Denmark: '',
    Djibouti: '',
    'Dominican Republic': '',
    Ecuador: '',
    Egypt: '',
    'El Salvador': '',
    Eritrea: '',
    Estonia: '',
    Ethiopia: '',
    Fiji: '',
    Finland: '',
    France: '',
    Gambia: '',
    Georgia: '',
    Germany: '',
    Ghana: '',
    'United Kingdom': '',
    Greece: '',
    Grenada: '',
    Guatemala: '',
    Guyana: '',
    'Hong Kong': '',
    Hungary: '',
    Iceland: '',
    India: '',
    Indonesia: '',
    Iran: '',
    Ireland: '',
    Israel: '',
    Italy: '',
    'Ivory Coast': '',
    Jamaica: '',
    Japan: '',
    Jordan: '',
    Kazakhstan: '',
    Kenya: '',
    Kuwait: '',
    Kyrgyzstan: '',
    Latvia: '',
    Lebanon: '',
    Lesotho: '',
    Liberia: '',
    Libya: '',
    Liechtenstein: '',
    Lithuania: '',
    Luxembourg: '',
    Malaysia: '',
    Mexico: '',
    Moldova: '',
    Mongolia: '',
    Morocco: '',
    Mozambique: '',
    Namibia: '',
    Netherlands: '',
    'New Zealand': '',
    Niger: '',
    Nigeria: '',
    'North Korea': '',
    Macedonia: '',
    Norway: '',
    Russia: '',
    Pakistan: '',
    Panama: '',
    Paraguay: '',
    Peru: '',
    Philippines: '',
    Poland: '',
    Portugal: '',
    'Puerto Rico': '',
    Qatar: '',
    Romania: '',
    Rwanda: '',
    Samoa: '',
    'San Marino': '',
    'São Tomé and Príncipe': '',
    Serbia: '',
    Seychelles: '',
    Singapore: '',
    Slovakia: '',
    Slovenia: '',
    'South Africa': '',
    'South Korea': '',
    Spain: '',
    'Sri Lanka': '',
    Sweden: '',
    Switzerland: '',
    Syria: '',
    Tanzania: '',
    Thailand: '',
    Togo: '',
    'Trinidad and Tobago': '',
    Tunisia: '',
    Turkey: '',
    Uganda: '',
    Ukraine: '',
    'United States': '',
    Uruguay: '',
    Uzbekistan: '',
    Venezuela: '',
    Vietnam: '',
    Zambia: '',
    Zimbabwe: '',
};

const CODES = {
    Andorra: 'ad',
    'United Arab Emirates': 'ae',
    Afghanistan: 'af',
    'Antigua and Barbuda': 'ag',
    Anguilla: 'ai',
    Albania: 'al',
    Armenia: 'am',
    'Netherlands Antilles': 'an',
    Angola: 'ao',
    'Asia/Pacific Region': 'ap',
    Antarctica: 'aq',
    Argentina: 'ar',
    'American Samoa': 'as',
    Austria: 'at',
    Australia: 'au',
    Aruba: 'aw',
    'Aland Islands': 'ax',
    Azerbaijan: 'az',
    'Bosnia and Herzegovina': 'ba',
    Barbados: 'bb',
    Bangladesh: 'bd',
    Belgium: 'be',
    'Burkina Faso': 'bf',
    Bulgaria: 'bg',
    Bahrain: 'bh',
    Burundi: 'bi',
    Benin: 'bj',
    Bermuda: 'bm',
    'Brunei Darussalam': 'bn',
    Bolivia: 'bo',
    Brazil: 'br',
    Bahamas: 'bs',
    Bhutan: 'bt',
    'Bouvet Island': 'bv',
    Botswana: 'bw',
    Belarus: 'by',
    Belize: 'bz',
    Canada: 'ca',
    'Cocos (Keeling) Islands': 'cc',
    'Congo, The Democratic Republic of the': 'cd',
    'Central African Republic': 'cf',
    Congo: 'cg',
    Switzerland: 'ch',
    'Ivory Coast': 'ci',
    'Cook Islands': 'ck',
    Chile: 'cl',
    Cameroon: 'cm',
    China: 'cn',
    Colombia: 'co',
    'Costa Rica': 'cr',
    Cuba: 'cu',
    'Cape Verde': 'cv',
    'Christmas Island': 'cx',
    Cyprus: 'cy',
    'Czech Republic': 'cz',
    Germany: 'de',
    Djibouti: 'dj',
    Denmark: 'dk',
    Dominica: 'dm',
    'Dominican Republic': 'do',
    Algeria: 'dz',
    Ecuador: 'ec',
    Estonia: 'ee',
    Egypt: 'eg',
    'Western Sahara': 'eh',
    Eritrea: 'er',
    Spain: 'es',
    Ethiopia: 'et',
    Europe: 'eu',
    Finland: 'fi',
    Fiji: 'fj',
    'Falkland Islands (Malvinas)': 'fk',
    'Micronesia, Federated States of': 'fm',
    'Faroe Islands': 'fo',
    France: 'fr',
    'France, Metropolitan': 'fx',
    Gabon: 'ga',
    'United Kingdom': 'gb',
    Grenada: 'gd',
    Georgia: 'ge',
    'French Guiana': 'gf',
    Guernsey: 'gg',
    Ghana: 'gh',
    Gibraltar: 'gi',
    Greenland: 'gl',
    Gambia: 'gm',
    Guinea: 'gn',
    Guadeloupe: 'gp',
    'Equatorial Guinea': 'gq',
    Greece: 'gr',
    'South Georgia and the South Sandwich Islands': 'gs',
    Guatemala: 'gt',
    Guam: 'gu',
    'Guinea-Bissau': 'gw',
    Guyana: 'gy',
    'Hong Kong': 'hk',
    'Heard Island and McDonald Islands': 'hm',
    Honduras: 'hn',
    Croatia: 'hr',
    Haiti: 'ht',
    Hungary: 'hu',
    Indonesia: 'id',
    Ireland: 'ie',
    Israel: 'il',
    'Isle of Man': 'im',
    India: 'in',
    'British Indian Ocean Territory': 'io',
    Iraq: 'iq',
    Iran: 'ir',
    Iceland: 'is',
    Italy: 'it',
    Jersey: 'je',
    Jamaica: 'jm',
    Jordan: 'jo',
    Japan: 'jp',
    Kenya: 'ke',
    Kyrgyzstan: 'kg',
    Cambodia: 'kh',
    Kiribati: 'ki',
    Comoros: 'km',
    'Saint Kitts and Nevis': 'kn',
    'North Korea': 'kp',
    'South Korea': 'kr',
    Kuwait: 'kw',
    'Cayman Islands': 'ky',
    Kazakhstan: 'kz',
    "Lao People's Democratic Republic": 'la',
    Lebanon: 'lb',
    'Saint Lucia': 'lc',
    Liechtenstein: 'li',
    'Sri Lanka': 'lk',
    Liberia: 'lr',
    Lesotho: 'ls',
    Lithuania: 'lt',
    Luxembourg: 'lu',
    Latvia: 'lv',
    Libya: 'ly',
    Morocco: 'ma',
    Monaco: 'mc',
    Moldova: 'md',
    Montenegro: 'me',
    Madagascar: 'mg',
    'Marshall Islands': 'mh',
    Macedonia: 'mk',
    Mali: 'ml',
    Myanmar: 'mm',
    Mongolia: 'mn',
    Macau: 'mo',
    'Northern Mariana Islands': 'mp',
    Martinique: 'mq',
    Mauritania: 'mr',
    Montserrat: 'ms',
    Malta: 'mt',
    Mauritius: 'mu',
    Maldives: 'mv',
    Malawi: 'mw',
    Mexico: 'mx',
    Malaysia: 'my',
    Mozambique: 'mz',
    Namibia: 'na',
    'New Caledonia': 'nc',
    Niger: 'ne',
    'Norfolk Island': 'nf',
    Nigeria: 'ng',
    Nicaragua: 'ni',
    Netherlands: 'nl',
    Norway: 'no',
    Nepal: 'np',
    Nauru: 'nr',
    Niue: 'nu',
    'New Zealand': 'nz',
    Oman: 'om',
    Panama: 'pa',
    Peru: 'pe',
    'French Polynesia': 'pf',
    'Papua New Guinea': 'pg',
    Philippines: 'ph',
    Pakistan: 'pk',
    Poland: 'pl',
    'Saint Pierre and Miquelon': 'pm',
    'Pitcairn Islands': 'pn',
    'Puerto Rico': 'pr',
    'Palestinian Territory': 'ps',
    Portugal: 'pt',
    Palau: 'pw',
    Paraguay: 'py',
    Qatar: 'qa',
    Reunion: 're',
    Romania: 'ro',
    Serbia: 'rs',
    Russia: 'ru',
    Rwanda: 'rw',
    'Saudi Arabia': 'sa',
    'Solomon Islands': 'sb',
    Seychelles: 'sc',
    Sudan: 'sd',
    Sweden: 'se',
    Singapore: 'sg',
    'Saint Helena': 'sh',
    Slovenia: 'si',
    'Svalbard and Jan Mayen': 'sj',
    Slovakia: 'sk',
    'Sierra Leone': 'sl',
    'San Marino': 'sm',
    Senegal: 'sn',
    Somalia: 'so',
    Suriname: 'sr',
    'São Tomé and Príncipe': 'st',
    'El Salvador': 'sv',
    Syria: 'sy',
    Swaziland: 'sz',
    'Turks and Caicos Islands': 'tc',
    Chad: 'td',
    'French Southern Territories': 'tf',
    Togo: 'tg',
    Thailand: 'th',
    Tajikistan: 'tj',
    Tokelau: 'tk',
    'Timor-Leste': 'tl',
    Turkmenistan: 'tm',
    Tunisia: 'tn',
    Tonga: 'to',
    Turkey: 'tr',
    'Trinidad and Tobago': 'tt',
    Tuvalu: 'tv',
    Taiwan: 'tw',
    Tanzania: 'tz',
    Ukraine: 'ua',
    Uganda: 'ug',
    'United States Minor Outlying Islands': 'um',
    'United States': 'us',
    Uruguay: 'uy',
    Uzbekistan: 'uz',
    'Holy See (Vatican City State)': 'va',
    'Saint Vincent and the Grenadines': 'vc',
    Venezuela: 've',
    'British Virgin Islands': 'vg',
    'U.S. Virgin Islands': 'vi',
    Vietnam: 'vn',
    Vanuatu: 'vu',
    'Wallis and Futuna': 'wf',
    Samoa: 'ws',
    Yemen: 'ye',
    Mayotte: 'yt',
    'South Africa': 'za',
    Zambia: 'zm',
    Zimbabwe: 'zw',
};

export const IMAGES = {
    ad: require('./media/flags/ad.png'),
    ae: require('./media/flags/ae.png'),
    af: require('./media/flags/af.png'),
    ag: require('./media/flags/ag.png'),
    ai: require('./media/flags/ai.png'),
    al: require('./media/flags/al.png'),
    am: require('./media/flags/am.png'),
    an: require('./media/flags/an.png'),
    ao: require('./media/flags/ao.png'),
    // ap: require('./media/flags/ap.png'),
    aq: require('./media/flags/aq.png'),
    ar: require('./media/flags/ar.png'),
    as: require('./media/flags/as.png'),
    at: require('./media/flags/at.png'),
    au: require('./media/flags/au.png'),
    aw: require('./media/flags/aw.png'),
    ax: require('./media/flags/ax.png'),
    az: require('./media/flags/az.png'),
    ba: require('./media/flags/ba.png'),
    bb: require('./media/flags/bb.png'),
    bd: require('./media/flags/bd.png'),
    be: require('./media/flags/be.png'),
    bf: require('./media/flags/bf.png'),
    bg: require('./media/flags/bg.png'),
    bh: require('./media/flags/bh.png'),
    bi: require('./media/flags/bi.png'),
    bj: require('./media/flags/bj.png'),
    bm: require('./media/flags/bm.png'),
    bn: require('./media/flags/bn.png'),
    bo: require('./media/flags/bo.png'),
    br: require('./media/flags/br.png'),
    bs: require('./media/flags/bs.png'),
    bt: require('./media/flags/bt.png'),
    bv: require('./media/flags/bv.png'),
    bw: require('./media/flags/bw.png'),
    by: require('./media/flags/by.png'),
    bz: require('./media/flags/bz.png'),
    ca: require('./media/flags/ca.png'),
    cc: require('./media/flags/cc.png'),
    cd: require('./media/flags/cd.png'),
    cf: require('./media/flags/cf.png'),
    cg: require('./media/flags/cg.png'),
    ch: require('./media/flags/ch.png'),
    ci: require('./media/flags/ci.png'),
    ck: require('./media/flags/ck.png'),
    cl: require('./media/flags/cl.png'),
    cm: require('./media/flags/cm.png'),
    cn: require('./media/flags/cn.png'),
    co: require('./media/flags/co.png'),
    cr: require('./media/flags/cr.png'),
    cu: require('./media/flags/cu.png'),
    cv: require('./media/flags/cv.png'),
    cx: require('./media/flags/cx.png'),
    cy: require('./media/flags/cy.png'),
    cz: require('./media/flags/cz.png'),
    de: require('./media/flags/de.png'),
    dj: require('./media/flags/dj.png'),
    dk: require('./media/flags/dk.png'),
    dm: require('./media/flags/dm.png'),
    do: require('./media/flags/do.png'),
    dz: require('./media/flags/dz.png'),
    ec: require('./media/flags/ec.png'),
    ee: require('./media/flags/ee.png'),
    eg: require('./media/flags/eg.png'),
    eh: require('./media/flags/eh.png'),
    er: require('./media/flags/er.png'),
    es: require('./media/flags/es.png'),
    et: require('./media/flags/et.png'),
    eu: require('./media/flags/eu.png'),
    fi: require('./media/flags/fi.png'),
    fj: require('./media/flags/fj.png'),
    fk: require('./media/flags/fk.png'),
    fm: require('./media/flags/fm.png'),
    fo: require('./media/flags/fo.png'),
    fr: require('./media/flags/fr.png'),
    // fx: require('./media/flags/fx.png'),
    ga: require('./media/flags/ga.png'),
    gb: require('./media/flags/gb.png'),
    gd: require('./media/flags/gd.png'),
    ge: require('./media/flags/ge.png'),
    gf: require('./media/flags/gf.png'),
    gg: require('./media/flags/gg.png'),
    gh: require('./media/flags/gh.png'),
    gi: require('./media/flags/gi.png'),
    gl: require('./media/flags/gl.png'),
    gm: require('./media/flags/gm.png'),
    gn: require('./media/flags/gn.png'),
    gp: require('./media/flags/gp.png'),
    gq: require('./media/flags/gq.png'),
    gr: require('./media/flags/gr.png'),
    gs: require('./media/flags/gs.png'),
    gt: require('./media/flags/gt.png'),
    gu: require('./media/flags/gu.png'),
    gw: require('./media/flags/gw.png'),
    gy: require('./media/flags/gy.png'),
    hk: require('./media/flags/hk.png'),
    hm: require('./media/flags/hm.png'),
    hn: require('./media/flags/hn.png'),
    hr: require('./media/flags/hr.png'),
    ht: require('./media/flags/ht.png'),
    hu: require('./media/flags/hu.png'),
    id: require('./media/flags/id.png'),
    ie: require('./media/flags/ie.png'),
    il: require('./media/flags/il.png'),
    im: require('./media/flags/im.png'),
    in: require('./media/flags/in.png'),
    io: require('./media/flags/io.png'),
    iq: require('./media/flags/iq.png'),
    ir: require('./media/flags/ir.png'),
    is: require('./media/flags/is.png'),
    it: require('./media/flags/it.png'),
    je: require('./media/flags/je.png'),
    jm: require('./media/flags/jm.png'),
    jo: require('./media/flags/jo.png'),
    jp: require('./media/flags/jp.png'),
    ke: require('./media/flags/ke.png'),
    kg: require('./media/flags/kg.png'),
    kh: require('./media/flags/kh.png'),
    ki: require('./media/flags/ki.png'),
    km: require('./media/flags/km.png'),
    kn: require('./media/flags/kn.png'),
    kp: require('./media/flags/kp.png'),
    kr: require('./media/flags/kr.png'),
    kw: require('./media/flags/kw.png'),
    ky: require('./media/flags/ky.png'),
    kz: require('./media/flags/kz.png'),
    la: require('./media/flags/la.png'),
    lb: require('./media/flags/lb.png'),
    lc: require('./media/flags/lc.png'),
    li: require('./media/flags/li.png'),
    lk: require('./media/flags/lk.png'),
    lr: require('./media/flags/lr.png'),
    ls: require('./media/flags/ls.png'),
    lt: require('./media/flags/lt.png'),
    lu: require('./media/flags/lu.png'),
    lv: require('./media/flags/lv.png'),
    ly: require('./media/flags/ly.png'),
    ma: require('./media/flags/ma.png'),
    mc: require('./media/flags/mc.png'),
    md: require('./media/flags/md.png'),
    me: require('./media/flags/me.png'),
    mg: require('./media/flags/mg.png'),
    mh: require('./media/flags/mh.png'),
    mk: require('./media/flags/mk.png'),
    ml: require('./media/flags/ml.png'),
    mm: require('./media/flags/mm.png'),
    mn: require('./media/flags/mn.png'),
    mo: require('./media/flags/mo.png'),
    mp: require('./media/flags/mp.png'),
    mq: require('./media/flags/mq.png'),
    mr: require('./media/flags/mr.png'),
    ms: require('./media/flags/ms.png'),
    mt: require('./media/flags/mt.png'),
    mu: require('./media/flags/mu.png'),
    mv: require('./media/flags/mv.png'),
    mw: require('./media/flags/mw.png'),
    mx: require('./media/flags/mx.png'),
    my: require('./media/flags/my.png'),
    mz: require('./media/flags/mz.png'),
    na: require('./media/flags/na.png'),
    nc: require('./media/flags/nc.png'),
    ne: require('./media/flags/ne.png'),
    nf: require('./media/flags/nf.png'),
    ng: require('./media/flags/ng.png'),
    ni: require('./media/flags/ni.png'),
    nl: require('./media/flags/nl.png'),
    no: require('./media/flags/no.png'),
    np: require('./media/flags/np.png'),
    nr: require('./media/flags/nr.png'),
    nu: require('./media/flags/nu.png'),
    nz: require('./media/flags/nz.png'),
    om: require('./media/flags/om.png'),
    pa: require('./media/flags/pa.png'),
    pe: require('./media/flags/pe.png'),
    pf: require('./media/flags/pf.png'),
    pg: require('./media/flags/pg.png'),
    ph: require('./media/flags/ph.png'),
    pk: require('./media/flags/pk.png'),
    pl: require('./media/flags/pl.png'),
    pm: require('./media/flags/pm.png'),
    pn: require('./media/flags/pn.png'),
    pr: require('./media/flags/pr.png'),
    ps: require('./media/flags/ps.png'),
    pt: require('./media/flags/pt.png'),
    pw: require('./media/flags/pw.png'),
    py: require('./media/flags/py.png'),
    qa: require('./media/flags/qa.png'),
    re: require('./media/flags/re.png'),
    ro: require('./media/flags/ro.png'),
    rs: require('./media/flags/rs.png'),
    ru: require('./media/flags/ru.png'),
    rw: require('./media/flags/rw.png'),
    sa: require('./media/flags/sa.png'),
    sb: require('./media/flags/sb.png'),
    sc: require('./media/flags/sc.png'),
    sd: require('./media/flags/sd.png'),
    se: require('./media/flags/se.png'),
    sg: require('./media/flags/sg.png'),
    sh: require('./media/flags/sh.png'),
    si: require('./media/flags/si.png'),
    sj: require('./media/flags/sj.png'),
    sk: require('./media/flags/sk.png'),
    sl: require('./media/flags/sl.png'),
    sm: require('./media/flags/sm.png'),
    sn: require('./media/flags/sn.png'),
    so: require('./media/flags/so.png'),
    sr: require('./media/flags/sr.png'),
    st: require('./media/flags/st.png'),
    sv: require('./media/flags/sv.png'),
    sy: require('./media/flags/sy.png'),
    sz: require('./media/flags/sz.png'),
    tc: require('./media/flags/tc.png'),
    td: require('./media/flags/td.png'),
    tf: require('./media/flags/tf.png'),
    tg: require('./media/flags/tg.png'),
    th: require('./media/flags/th.png'),
    tj: require('./media/flags/tj.png'),
    tk: require('./media/flags/tk.png'),
    tl: require('./media/flags/tl.png'),
    tm: require('./media/flags/tm.png'),
    tn: require('./media/flags/tn.png'),
    to: require('./media/flags/to.png'),
    tr: require('./media/flags/tr.png'),
    tt: require('./media/flags/tt.png'),
    tv: require('./media/flags/tv.png'),
    tw: require('./media/flags/tw.png'),
    tz: require('./media/flags/tz.png'),
    ua: require('./media/flags/ua.png'),
    ug: require('./media/flags/ug.png'),
    um: require('./media/flags/um.png'),
    us: require('./media/flags/us.png'),
    uy: require('./media/flags/uy.png'),
    uz: require('./media/flags/uz.png'),
    va: require('./media/flags/va.png'),
    vc: require('./media/flags/vc.png'),
    ve: require('./media/flags/ve.png'),
    vg: require('./media/flags/vg.png'),
    vi: require('./media/flags/vi.png'),
    vn: require('./media/flags/vn.png'),
    vu: require('./media/flags/vu.png'),
    wf: require('./media/flags/wf.png'),
    ws: require('./media/flags/ws.png'),
    ye: require('./media/flags/ye.png'),
    yt: require('./media/flags/yt.png'),
    za: require('./media/flags/za.png'),
    zm: require('./media/flags/zm.png'),
    zw: require('./media/flags/zw.png'),
};

Object.keys(CODES).map(k => {
    COUNTRIES[k] = CODES[k];
});

export default COUNTRIES;
