export default {
    tennis: 'Tennis',
    golf: 'Golf',
    'gymnastics-artistic': 'Artistic Gymnastics',
    taekwondo: 'Taekwondo',
    'sport-climbing': 'Sport Climbing',
    'baseball-softball': 'Baseball/Softball',
    badminton: 'Badminton',
    skateboarding: 'Skateboarding',
    handball: 'Handball',
    diving: 'Diving',
    shooting: 'Shooting',
    'equestrian---dressage': 'Equestrian',
    karate: 'Karate',
    triathlon: 'Triathlon',
    basketball: ['3x3 Basketball', "Basketball"],
    'equestrian-jumping': 'Equestrian',
    'table-tennis': 'Table Tennis',
    fencing: 'Fencing',
    boxing: 'Boxing',
    'marathon-swimming': 'Marathon Swimming',
    'cycling-road': 'Cycling Road',
    'modern-pentathlon': 'Modern Pentathlon',
    hockey: 'Hockey',
    'water-polo': 'Water Polo',
    trampoline: 'Trampoline Gymnastics',
    'cycling-bmx': 'BMX Racing',
    'canoe-sprint': 'Sprint',
    'gymnastics-rhythmic': 'Rhythmic Gymnastics',
    football: 'Football',
    'wrestling-freestyle': 'Wrestling',
    'equestrian-eventing': 'Equestrian',
    weightlifting: 'Weightlifting',
    rugby: 'Rugby',
    'beach-volleyball': 'Beach Volleyball',
    archery: 'Archery',
    surfing: 'Surfing',
    judo: 'Judo',
    'canoe-slalom': 'Canoe Slalom',
    sailing: 'Sailing',
    rowing: 'Rowing',
    'cycling-track': 'Cycling Track',
    'wrestling-greco-roman': 'Wrestling',
    volleyball: 'Volleyball',
    'artistic-swimming': 'Artistic Swimming',
    'cycling-mountain-bike': 'Cycling Mountain Bike',
    athletics: 'Athletics',
    swimming: 'Swimming',
};
