require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'cytechtokyo2021' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  use_flipper!
  post_install do |installer|
     flipper_post_install(installer)
  end

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

end
